### PR TITLE
Karam dosa added

### PR DESCRIPTION
**Pull request by Mohansai7-ctrl**
We added another type of dosa which is karam dosa

We introduced this becuase karam will be added as an extra ingrediant so that it increases the taste.

### CODE REVIEW

**Review by saitest-ui — COMMENTED** [review]
Why did you added karam ingrediant?
what is the percentage of sales getting increased by adding this ingrediant? becuase investment should not be greater than the sales/profits.

**Comment by Mohansai7-ctrl** [comment]
> Why did you added karam ingrediant? what is the percentage of sales getting increased by adding this ingrediant? becuase investment should not be greater than the sales/profits.

Hi, we have added becuse to increase the taste.
I cannot predict the exact percentage of sales increased, but im sure that sales will be increased vigorously and profits will be increased compared with investment.

**Comment by saitest-ui** [comment]
> > Why did you added karam ingrediant? what is the percentage of sales getting increased by adding this ingrediant? becuase investment should not be greater than the sales/profits.
> 
> Hi, we have added becuse to increase the taste. I cannot predict the exact percentage of sales increased, but im sure that sales will be increased vigorously and profits will be increased compared with investment.

ah then good, approving it now.

**Review by saitest-ui — APPROVED** [review]
Good changes, approving for rebase.

**Pull request merged**
